# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Enter < Formula
  desc "Show contextual info when you press Enter on an empty prompt"
  homepage "https://github.com/babarot/enter"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/babarot/enter/releases/download/v0.4.0/enter_Darwin_x86_64.tar.gz"
      sha256 "7c19a815107616af7d66e8164a1382c23529c2a5dd23ee6bbbfc7951dce9505e"

      define_method(:install) do
        bin.install "enter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/babarot/enter/releases/download/v0.4.0/enter_Darwin_arm64.tar.gz"
      sha256 "5953075352e24f98472eadf580a7896275aaadf26ce6d52a1ff29d697e8ee721"

      define_method(:install) do
        bin.install "enter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/babarot/enter/releases/download/v0.4.0/enter_Linux_x86_64.tar.gz"
      sha256 "cb9d9a060bc5918198e70012f6b621a196e962634b5493260563057d7102dbdb"
      define_method(:install) do
        bin.install "enter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/babarot/enter/releases/download/v0.4.0/enter_Linux_arm64.tar.gz"
      sha256 "64cb3c84112e07af7b8c8db24397792a70a6f5ce7edd1920bc293c5d6dbdf048"
      define_method(:install) do
        bin.install "enter"
      end
    end
  end
end
