# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhInfra < Formula
  desc "A gh extension for infrastructure management"
  homepage "https://github.com/babarot/gh-infra"
  version "0.13.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/babarot/gh-infra/releases/download/v0.13.0/gh-infra_darwin_amd64.tar.gz"
      sha256 "a86f2c0824df74c05718ed1bb95b6cb6e3ed078631a858e8bab5b906026be6fb"

      define_method(:install) do
        bin.install "gh-infra"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/babarot/gh-infra/releases/download/v0.13.0/gh-infra_darwin_arm64.tar.gz"
      sha256 "bd40cc3ab679d95e1c23dc68f5e15214b873066e21500e63cf4c32d10c401460"

      define_method(:install) do
        bin.install "gh-infra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/babarot/gh-infra/releases/download/v0.13.0/gh-infra_linux_amd64.tar.gz"
      sha256 "46d236f9bc4352654b32213c1638a4451a343e9c37358428083d268f44593c27"
      define_method(:install) do
        bin.install "gh-infra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/babarot/gh-infra/releases/download/v0.13.0/gh-infra_linux_arm64.tar.gz"
      sha256 "ca877eabc46f3c79f1fee9b032b6cbe7d571defad8485902d03134cd2dc51961"
      define_method(:install) do
        bin.install "gh-infra"
      end
    end
  end
end
