# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gomi < Formula
  desc "A Safer Alternative to the UNIX rm Command!"
  homepage "https://gomi.dev"
  version "1.6.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/babarot/gomi/releases/download/v1.6.2/gomi_Darwin_x86_64.tar.gz"
      sha256 "16c914a164a3090433fd07aeb228491d47e3cec00c82c2a46ad08479c4ccab59"

      def install
        bin.install "gomi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/babarot/gomi/releases/download/v1.6.2/gomi_Darwin_arm64.tar.gz"
      sha256 "eb7fe5cfb2c2f89d408ad18ed022e90a7eef480a9ddf207026a51395b9a8a3c4"

      def install
        bin.install "gomi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/babarot/gomi/releases/download/v1.6.2/gomi_Linux_x86_64.tar.gz"
      sha256 "179176bcb5d4d92cfbd13dfd70764e41f1f98c33d739409e2e9e2fc595423d08"
      def install
        bin.install "gomi"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/babarot/gomi/releases/download/v1.6.2/gomi_Linux_armv6.tar.gz"
      sha256 "c2469014e32a27d3d2b84fd136f4ebdce2a982d9a21d3e34ef585cc69a2ebcb9"
      def install
        bin.install "gomi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/babarot/gomi/releases/download/v1.6.2/gomi_Linux_arm64.tar.gz"
      sha256 "af7f08f83062c905ea1e3777c42b09938b116f523efd66de0de5174eb438b2f3"
      def install
        bin.install "gomi"
      end
    end
  end
end
