# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Naminator < Formula
  desc "Bulk-rename w/ EXIF metadata"
  homepage "https://github.com/babarot/naminator"
  version "0.2.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/babarot/naminator/releases/download/v0.2.5/naminator_Darwin_x86_64.zip"
      sha256 "ea0df5e75a409e5e979acfbeadf96a36845573744a4f26ff950ca0254fcebc32"

      define_method(:install) do
        bin.install "naminator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/babarot/naminator/releases/download/v0.2.5/naminator_Darwin_arm64.zip"
      sha256 "3f427922442b6bc0284cb133ac5216001e0edcc023b5b6b68c4b86584200fc2d"

      define_method(:install) do
        bin.install "naminator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/babarot/naminator/releases/download/v0.2.5/naminator_Linux_x86_64.tar.gz"
      sha256 "27a3e1e11f71cfb403ab14b435064ed57e23a622ea734ff138f7ae5ed5530e11"
      define_method(:install) do
        bin.install "naminator"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/babarot/naminator/releases/download/v0.2.5/naminator_Linux_arm64.tar.gz"
      sha256 "ccb33922a2d5438bdc697585251393962be5f22d9f607d57db5579d6725d31ae"
      define_method(:install) do
        bin.install "naminator"
      end
    end
  end
end
