# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Naminator < Formula
  desc "Bulk-rename w/ EXIF metadata"
  homepage "https://github.com/babarot/naminator"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/babarot/naminator/releases/download/v0.2.3/naminator_Darwin_x86_64.zip"
      sha256 "26b5a3a4ab8d1b2de105d751137c224ace721b163417908a2a15c8f25b45b8a2"

      def install
        bin.install "naminator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/babarot/naminator/releases/download/v0.2.3/naminator_Darwin_arm64.zip"
      sha256 "58fe018f2fbb32ad0ae935c62c571f966ea921b33472e2d6821b78bf87253edb"

      def install
        bin.install "naminator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/babarot/naminator/releases/download/v0.2.3/naminator_Linux_x86_64.tar.gz"
        sha256 "85e9067282b1f0bf8b8dac82e7bda39598e7451ea3275ffbd9c2be162990c122"

        def install
          bin.install "naminator"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/babarot/naminator/releases/download/v0.2.3/naminator_Linux_arm64.tar.gz"
        sha256 "ac6e371577f01cdbfdf75fa69a4f44aceebf12d16431e8caf020e05a2517c5d3"

        def install
          bin.install "naminator"
        end
      end
    end
  end
end
