# This file was generated by GoReleaser. DO NOT EDIT.
class Gist < Formula
  desc "A simple gist editor for CLI"
  homepage "https://github.com/b4b4r07/gist"
  version "1.2.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/b4b4r07/gist/releases/download/v1.2.4/gist_darwin_x86_64.tar.gz"
    sha256 "fb827b437825798f892d417c36595d773351689c4fefcfabb7eb5f1fbee117fb"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/b4b4r07/gist/releases/download/v1.2.4/gist_linux_x86_64.tar.gz"
      sha256 "03ffa794b2492a71565ded48587495b6ab60d3ccefa7a7523496821151c611b0"
    end
  end

  def install
    bin.install "gist"
  end

  test do
    system "#{bin}/gist", "--version"
  end
end
