# This file was generated by GoReleaser. DO NOT EDIT.
class Gomi < Formula
  desc "Replacement for UNIX rm command!"
  homepage "https://github.com/b4b4r07/gomi"
  version "1.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/b4b4r07/gomi/releases/download/v1.1.1/gomi_darwin_x86_64.tar.gz"
    sha256 "4f7fd3c4818806c35d9475690aba53062ad9cc1ddd6fa47fbf818110923a749f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/b4b4r07/gomi/releases/download/v1.1.1/gomi_linux_x86_64.tar.gz"
      sha256 "e3669935e95eac76af7c9c35fb728ef06fcb1e2358f7a0157bc2f02d6dc5888b"
    end
  end

  def install
    bin.install "gomi"
  end

  test do
    system "#{bin}/gomi", "--version"
  end
end
