# This file was generated by GoReleaser. DO NOT EDIT.
class Stein < Formula
  desc "A linter for config files with a customizable rule set"
  homepage "https://github.com/b4b4r07/stein"
  version "0.3.4"

  if OS.mac?
    url "https://github.com/b4b4r07/stein/releases/download/v0.3.4/stein_darwin_x86_64.tar.gz"
    sha256 "0eb362f82d4c2a9383b61a236ed5bfb258de406e8e25b24b5c4668df1dbd8c25"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/b4b4r07/stein/releases/download/v0.3.4/stein_linux_x86_64.tar.gz"
      sha256 "1bbf9726f2537472f44abf1aa3d6b8bb14224989f7e5b9daba05e9c0b68a506b"
    end
  end

  def install
    bin.install "stein"
  end

  test do
    system "#{bin}/stein", "--version"
  end
end
